name: Deploy to Server

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发部署

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy code to server
      run: |
        ssh -o StrictHostKeyChecking=no your_username@your-server-ip "cd /path/to/your/project && git pull origin main"
